### ISSUE TITLE
New Website Logo: Tombikus

### ISSUE THREAD

**Issue by tombikus** [sdogruyol/friends-of-crystal#1]
To list your organization's logo on Friends of Crystal website, fill out the following information and click "submit new issue".

- Organization name: (as you want it displayed)
- Homepage url: (homepage/primary entry point for users)
- Logo url: (svg if possible, pngs over 400x200px with transparent backgrounds are also acceptable)
- How you are using Crystal: (one sentence describing your use of Crystal)
- Url describing Crystal usage: (optional link to e.g. blog post explaining how you use Crystal)
- Organization contact: (name and email. we may contact you when updating this page.

**Comment by sdogruyol** [comment]
This looks like a dummy..closing
