### ISSUE TITLE
New Website Logo: DIGIO Digital Solutions

### ISSUE THREAD

**Issue by sevir** [sdogruyol/friends-of-crystal#10]
To list your organization's logo on Friends of Crystal website, fill out the following information and click "submit new issue".

- Organization name: DIGIO Digital Solutions
- Homepage url: https://www.digio.es
- Logo url (400x400): https://drive.google.com/file/d/1Dqrc1HDu6U1y_ssDp9wILWbku56Wj-KM/view?usp=sharing
- How you are using Crystal: Microservices for Artificial Vision Platform
- Url describing Crystal usage: <none>
- Organization contact: Jose F. Rives <jose@digio.es>

**Comment by sdogruyol** [comment]
Thank you!
