### ISSUE TITLE
New Website Logo: FullCycle

### ISSUE THREAD

**Issue by hako** [sdogruyol/friends-of-crystal#11]
To list your organization's logo on Friends of Crystal website, fill out the following information and click "submit new issue".

- Organization name: FullCycle
- Homepage url: https://fullcycle.app
- Logo url (400x400): https://drive.google.com/file/d/1daHxR0kP7HbT5qarr3g555z8h65iETTn/view?usp=sharing
- How you are using Crystal: APIs and Data transformation
- Url describing Crystal usage: 
- Organization contact: Wesley Hill - wesley @ fullcycle [dot] app

**Comment by sdogruyol** [comment]
Thank you!
