### ISSUE TITLE
New Website Logo: altrady

### ISSUE THREAD

**Issue by benoist** [sdogruyol/friends-of-crystal#12]
To list your organization's logo on Friends of Crystal website, fill out the following information and click "submit new issue".

- Organization name: altrady
- Homepage url: https://altrady.com
- Logo url (400x400): https://cdn.altrady.com/static/icon-400x400.png
- How you are using Crystal: Crypto Base Scanner algorithm calculations
- Organization contact: benoist@altrady.com

**Comment by sdogruyol** [comment]
Thank you!
