### ISSUE TITLE
NeuraLegion info update

### ISSUE THREAD

**Issue by ArtLinkov** [sdogruyol/friends-of-crystal#13]
Hey @sdogruyol :wave::grin:, 
Any chance to update our tagline to: **"SDLC integrated Dynamic Application Security Testing"**

 And our logo to this version with padding? (to avoid cropping by the circle)
![NeuraLegion Shield 400x400 2](https://user-images.githubusercontent.com/29929418/69497523-9ac39f80-0ee6-11ea-85af-4f5e344fddcf.png)

Thanks man!

**Comment by sdogruyol** [comment]
Updated, thanks!
