### ISSUE TITLE
New Website Logo: Neopoly

### ISSUE THREAD

**Issue by shluboto** [sdogruyol/friends-of-crystal#18]
- Organization name: Neopoly
- Homepage url: https://www.neopoly.com
- Logo url (400x400): https://www.neopoly.de/ftp/neo_logo_400x400.png
- How you are using Crystal: Intensive sorting, micro services, APIse
- Url describing Crystal usage: none
- Organization contact: Andreas Busold, ab@neopoly.de

**Comment by sdogruyol** [comment]
Updated 👍
