### ISSUE TITLE
New Website Logo: xevIT networks

### ISSUE THREAD

**Issue by mavu** [sdogruyol/friends-of-crystal#2]
To list your organization's logo on Friends of Crystal website, fill out the following information and click "submit new issue".

- Organization name: xevIT net works
- Homepage url: xevit.com
- Logo url: https://www.xevit.com/sites/all/themes/bmh/logo.png
- How you are using Crystal: Connecting IoT and Telecommunications 
- Organization contact: marco.vujevic (at) xevit.com

**Comment by sdogruyol** [comment]
@mavu I'm sorry, do you have a 400x400 logo? Friends of Crystal is still WIP and I need to update the issue template to actually ask for a 400x400 logo :)

**Comment by mavu** [comment]
this is 400x400, but the logo itself is still 400x95, the rest should be transparent.
I hope :)
![logo_400x400](https://user-images.githubusercontent.com/160951/67149704-c7184a80-f2ae-11e9-9512-8475095fb1dd.png)

**Comment by sdogruyol** [comment]
Done, thanks @mavu :+1:
