### ISSUE TITLE
New Website Logo: WeTransfer

### ISSUE THREAD

**Issue by WJWH** [sdogruyol/friends-of-crystal#4]
To list your organization's logo on Friends of Crystal website, fill out the following information and click "submit new issue".

- Organization name: WeTransfer
- Homepage url: https://wetransfer.com
- Logo url (400x400): 
![WT_Wordmark_400px](https://user-images.githubusercontent.com/2591792/67271996-f51eaa00-f4bb-11e9-8866-a9fba4acf30e.png)

- How you are using Crystal: Large scale file streaming.
- Url describing Crystal usage: We don't yet have a blog post about our Crystal usage yet but are planning to write one in the future.
- Organization contact: Wander Hillen. Email is wander@wetransfer.com

**Comment by sdogruyol** [comment]
Thank you!
