### ISSUE TITLE
New Website Logo: ACAEngine

### ISSUE THREAD

**Issue by KimBurgess** [sdogruyol/friends-of-crystal#6]
To list your organization's logo on Friends of Crystal website, fill out the following information and click "submit new issue".

- Organization name: ACAEngine
- Homepage url: [https://acaengine.com/](https://acaprojects.com/)
- Logo url (400x400):
![ACAEngine Logo](https://avatars0.githubusercontent.com/u/13131204?s=400&u=2ad37c30d8d7d8b2f9c7482cab55bfd31b8b51a6&v=4)
- How you are using Crystal: APIs for physical environments (full stack: https://github.com/aca-labs/)
- Url describing Crystal usage: https://acaprojects.com/the-aca-blog/2019/3/18/introducing-spider-gazelle-our-open-source-web-framework
- Organization contact: kim@acaprojects.com

**Comment by sdogruyol** [comment]
Thank you!
