### ISSUE TITLE
New Website Logo: Runcite

### ISSUE THREAD

**Issue by ld100** [sdogruyol/friends-of-crystal#7]
To list your organization's logo on Friends of Crystal website, fill out the following information and click "submit new issue".

- Organization name: Runcite
- Homepage url: https://runcite.com
- Logo url https://static.tildacdn.com/tild3630-6163-4239-b266-393664376532/rc_red.svg
- How you are using Crystal: Microservices using Lucky and Sidekiq.cr
- Url describing Crystal usage: -
- Organization contact: Alexander Lockshyn <alex@runcite.com>

**Comment by sdogruyol** [comment]
Thanks, Do you have a 400x400 png for the logo

**Comment by sdogruyol** [comment]
Ping @ld100 , any update on this?

**Comment by ld100** [comment]
Please disregard this, we've abandoned Crystal.
