### ISSUE TITLE
New Website Logo: Blitline

### ISSUE THREAD

**Issue by blitline-dev** [sdogruyol/friends-of-crystal#8]
To list your organization's logo on Friends of Crystal website, fill out the following information and click "submit new issue".

- Organization name: Blitline
- Homepage url: http://www.blitline.com
- Logo url (400x400):  https://blitdoc.s3.amazonaws.com/logos/box_icon/logo_400x400.png
- How you are using Crystal: We have a number of custom micro-services written using crystal, including our logging platform, our job queue, and our key/value store.
- Url describing Crystal usage: We don't have a blog about our Crystal use, but we will be presenting a talk at the Chicago Crystal Meetup (https://www.meetup.com/Crystal-Lang-Chicago/events/264935336/?_xtd=gatlbWFpbF9jbGlja9oAJDc3N2E3M2MxLTdlMTEtNDlmYS1hNjVjLTAyNDQ0NmFiNTJhOQ&_af=event&_af_eid=264935336) about our use of crystal and the services we run
- Organization contact: Jason Malcolm (jason@blitline.com)

**Comment by sdogruyol** [comment]
Thank you!
