### ISSUE TITLE
New Website Logo: Symposium Events

### ISSUE THREAD

**Issue by sevir** [sdogruyol/friends-of-crystal#9]
To list your organization's logo on Friends of Crystal website, fill out the following information and click "submit new issue".

- Organization name: Symposium Events · The event management platform preferred by Universities
- Homepage url: https://symposium.events
- Logo url (400x400): https://drive.google.com/file/d/1KRiV721FZe20oAYNWUMsljvK3ZcVoRg8/view?usp=sharing
- How you are using Crystal: Microservices connecting Spanish Public Treasury and the public universities.
- Url describing Crystal usage: <none>
- Organization contact: Jose F. Rives <jose@digio.es>

**Comment by sdogruyol** [comment]
Thank you!
